server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/cloud_order?useSSL=false
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice  # 服务名称
  cloud:
    nacos: # nacos服务发现。用它就需要注释掉下面的eureka。
      server-addr: localhost:8848   #nacos服务地址。貌似默认就是这个不配也行。
#      discovery:
#        namespace: 77c261e4-1109-47c8-8209-b3bebceaafa6 #namespace的ID!!!。注意如果这么配置的话，order服务就和user服务不在一个命名空间了，order服务会无法调用user了。所以注释掉。
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#用nacos做服务注册，所以注释掉下面的eureka
#eureka:
#  client:
#    service-url:  # eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka