server:
  port: 10010 #网关端口
spring:
  application:
    name: gateway #服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
    gateway:
      routes: #网关路由配置
        - id: user-service # 路由 id ，自定义，只要唯一即可
          # uri: http://127.0.0.1:8081 # 路由的目标地址 http就是固定地址
          uri: lb://userservice #路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/user/** # 这个是按照路径匹配，只要以/user/开头就符合要求
          filters: # p38路由过滤器：过滤器，只对user-service生效。会覆盖default-filters的同名配置。
            - AddRequestHeader=newHeaderKey, newHeaderValue --- user-service only!!!
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
      default-filters:  # p38路由过滤器：默认过滤器，对全局所有路由生效。优先级低于各路由各自配置的路由过滤器。
        - AddRequestHeader=newHeaderKey, newHeaderValue --- default all filters!!!